### ISSUE TITLE
PixelPusher protocol description

### ISSUE THREAD

**Issue by ilfirin-ms** [hzeller/pixelpusher-server#2]
It would be nice, if some description or link is provided to describe pixelpusher protocol. Also brief comparison to Flashen Taschen.

**Comment by hzeller** [comment]
The PixelPusher protocol is just a implementation of the http://www.heroicrobotics.com/products/pixelpusher hardware device. I don't know if there is an official documentation, but the best thing is essentially looking at the header https://github.com/hzeller/pixelpusher-server/blob/master/lib/universal-discovery-protocol.h that I received from them, then implemented from there.

PixelPusher is primarily a protocol that controls LED strips. 2D displays can be done by arranging parallel LED strips. It has features to control the refresh rate by reporting its processing time so that the server can slow down if needed. It is primarily nice for light-effect controls.

The FlaschenTaschen protocol is primarily a 2D pixel protocol that allows compositing of stacked square regions on a display; it is primarily nice if sending images or video is the primary goal.
https://github.com/hzeller/flaschen-taschen/blob/master/doc/protocols.md

**Comment by ilfirin-ms** [comment]
That was fast. Thank you
